server:
  port: 8081

spring:
  application:
    name: springcloud-ddd-crash-demo
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8989/eureka/